name: Publish from master

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  publish:
    name: Publish
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Install semantic-release extra plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Buil storybook
        run: npm run storybook:build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org:8443/
          CI: true
          HUSKY: 0
        run: npx semantic-release
      - name: Deploy storybook
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: storybook-static
